const cfg = window.CHONG_CONFIG || {};
const api = (cfg.API_BASE_URL || "").replace(/\/$/, "");
const state = JSON.parse(localStorage.getItem("chong-state") || '{"score":0,"done":[]}');
const MEMORY_KEY = "chong-wise-memory-v1";
const PERSONALITY_KEY = "chong-personality-v1";
let memory = JSON.parse(localStorage.getItem(MEMORY_KEY) || "[]");
const config = { voiceReply: false, nitro: false, sources: false, wise: true, attachment: null, audioFiles: [] };
const personality = JSON.parse(localStorage.getItem(PERSONALITY_KEY) || '{"accent":"#7fd0ff","motion":true}');
const missions = [{id:"visita",name:"Visitar el centro de mando",pts:10},{id:"chat",name:"Hablar con Chongoku",pts:20},{id:"apoyo",name:"Explorar las opciones de apoyo",pts:15}];
const $ = (selector) => document.querySelector(selector);
const messages = $("#messages"), form = $("#chatForm"), field = $("#message"), status = $("#chatStatus"), fileInput = $("#fileInput"), fileName = $("#fileName");

function remember(role, text) { if (!config.wise || !text) return; memory.push({role,text:String(text).slice(0,800)}); memory=memory.slice(-20); localStorage.setItem(MEMORY_KEY,JSON.stringify(memory)); }
function save(){localStorage.setItem("chong-state",JSON.stringify(state));$("#score").textContent=state.score;}
function renderMissions(){const box=$("#missions");box.textContent="";missions.forEach(m=>{const label=document.createElement("label"),input=document.createElement("input");label.className="mission";input.type="checkbox";input.checked=state.done.includes(m.id);input.addEventListener("change",()=>{if(input.checked&&!state.done.includes(m.id)){state.done.push(m.id);state.score+=m.pts;}if(!input.checked&&state.done.includes(m.id)){state.done=state.done.filter(id=>id!==m.id);state.score=Math.max(0,state.score-m.pts);}save();});label.append(input,document.createTextNode(`${m.name} (+${m.pts})`));box.append(label);});}

function appendInlineMarkdown(container,text){const token=/(\*\*[^*]+\*\*|_[^_\n]+_|`[^`\n]+`|\[[^\]]+\]\(https:\/\/[^)\s]+\))/g;let last=0,match;while((match=token.exec(text))){if(match.index>last)container.append(document.createTextNode(text.slice(last,match.index)));const value=match[0];if(value.startsWith("**")){const strong=document.createElement("strong");strong.textContent=value.slice(2,-2);container.append(strong);}else if(value.startsWith("_")){const em=document.createElement("em");em.textContent=value.slice(1,-1);container.append(em);}else if(value.startsWith("`")){const code=document.createElement("code");code.textContent=value.slice(1,-1);container.append(code);}else{const parts=value.match(/^\[([^\]]+)\]\((https:\/\/[^)]+)\)$/),a=document.createElement("a");a.textContent=parts[1];a.href=parts[2];a.target="_blank";a.rel="noopener noreferrer";container.append(a);}last=token.lastIndex;}if(last<text.length)container.append(document.createTextNode(text.slice(last)));}
function appendMarkdownLines(container,text){let list=null,listType="";String(text).split(/\r?\n/).forEach(line=>{const heading=line.match(/^(#{1,3})\s+(.+)/),unordered=line.match(/^\s*[-*]\s+(.+)/),ordered=line.match(/^\s*\d+[.)]\s+(.+)/),quote=line.match(/^>\s?(.+)/);if(!line.trim()){list=null;listType="";return;}if(unordered||ordered){const type=ordered?"ol":"ul";if(!list||listType!==type){list=document.createElement(type);container.append(list);listType=type;}const li=document.createElement("li");appendInlineMarkdown(li,(ordered||unordered)[1]);list.append(li);return;}list=null;listType="";const block=document.createElement(heading?`h${Math.min(4,heading[1].length+2)}`:quote?"blockquote":"p");appendInlineMarkdown(block,heading?heading[2]:quote?quote[1]:line);container.append(block);});}
async function copyText(text){const value=String(text);if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value);return;}const area=document.createElement("textarea");area.value=value;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();const copied=document.execCommand("copy");area.remove();if(!copied)throw new Error("No se pudo copiar");}
function copyButton(label="📋 Copiar"){const button=document.createElement("button");button.type="button";button.className="copyMessage";button.textContent=label;button.setAttribute("aria-label","Copiar mensaje");return button;}
function addRichText(container,text){const regex=/```([\w+-]*)\n?([\s\S]*?)```/g;let last=0,match;while((match=regex.exec(text))){if(match.index>last)appendMarkdownLines(container,text.slice(last,match.index));const pre=document.createElement("pre"),code=document.createElement("code"),button=copyButton("📋 Copiar código"),codeText=match[2];code.textContent=codeText;code.className=match[1]?`language-${match[1]}`:"";pre.append(code);button.classList.add("copyCode");button.addEventListener("click",async event=>{event.stopPropagation();try{await copyText(codeText);button.textContent="✅ Copiado";}catch{button.textContent="No se pudo copiar";}setTimeout(()=>button.textContent="📋 Copiar código",2000);});container.append(pre,button);last=regex.lastIndex;}if(last<text.length)appendMarkdownLines(container,text.slice(last));}
function bubble(text,kind,sources=[]){const article=document.createElement("article"),raw=String(text);article.className=`bubble ${kind}`;const content=document.createElement("div"),button=copyButton();content.className="markdownBody";addRichText(content,raw);button.addEventListener("click",async()=>{try{await copyText(raw);button.textContent="✅ Copiado";}catch{button.textContent="No se pudo copiar";}setTimeout(()=>button.textContent="📋 Copiar",2000);});article.append(content,button);if(sources.length){const list=document.createElement("ul");list.className="sourceList";sources.forEach(source=>{try{const url=new URL(source.url);if(url.protocol!=="https:")return;const li=document.createElement("li"),a=document.createElement("a");a.href=url.href;a.target="_blank";a.rel="noopener noreferrer";a.textContent=source.title||url.hostname;li.append(a);list.append(li);}catch{}});if(list.children.length)article.append(list);}messages.append(article);messages.scrollTop=messages.scrollHeight;}
function setChatOpen(open){const chat=$(".chat"),toggle=$("#chatToggle");chat.classList.toggle("closed",!open);toggle.textContent=open?"—":"+";toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?"Minimizar chat":"Abrir chat");}
function savePersonality(){localStorage.setItem(PERSONALITY_KEY,JSON.stringify(personality));document.documentElement.style.setProperty("--accent",personality.accent);document.body.classList.toggle("no-motion",!personality.motion);$("#accentPicker").value=personality.accent;$("#motionToggle").checked=personality.motion;}
const otterLines=["¡Tripulación lista! 🦦🚀","La nutria detectó curiosidad en la cabina.","Consejo orbital: preguntá cualquier cosa al tutor.","Modo caguama cósmica activado con responsabilidad."];
const surprisePrompts=["explica por qué brillan las estrellas","ejercicio de lógica para principiantes","resumen sobre energías limpias","explica cómo funciona la inteligencia artificial"];
function playWithOtter(){const orb=$("#otterOrb");orb.classList.remove("play");void orb.offsetWidth;orb.classList.add("play");$("#otterMood").textContent=otterLines[Math.floor(Math.random()*otterLines.length)];if(personality.motion)document.querySelectorAll(".floatActions button").forEach(button=>{button.style.setProperty("--jx",`${Math.round(Math.random()*18-9)}px`);button.style.setProperty("--jy",`${Math.round(Math.random()*18-9)}px`);});setTimeout(()=>orb.classList.remove("play"),700);}
function speak(text){if(!config.voiceReply||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text).replace(/```[\s\S]*?```/g," bloque de código "));u.lang="es-MX";u.rate=.95;speechSynthesis.speak(u);}
function localReply(text){const n=text.toLocaleLowerCase("es").trim();if(n==="ayuda")return"Comandos del tutor:\n• explica [tema]: explicación paso a paso.\n• ejercicio [tema]: práctica con pista y solución.\n• resumen [tema]: síntesis con ideas clave.\nTambién podés hablar, subir archivos o cargar dos audios para mezclarlos.";if(/^(hola|buenas|qué onda|que onda|hey)\b/.test(n))return"Qué onda, astronauta. Decime qué querés aprender y lo vemos paso a paso.";if(n.length<4||/^(algo|dime|qué|que|no sé|no se)$/.test(n))return"Contame el tema y qué necesitás: una explicación, un ejercicio o un resumen.";return null;}
async function attachmentContext(){const f=config.attachment;if(!f)return"";if(f.size>2_000_000)throw new Error("El archivo supera 2 MB. Reducilo antes de enviarlo.");if(/^(text\/|application\/(json|csv))/.test(f.type)||/\.(txt|md|csv|json)$/i.test(f.name))return`\n\nArchivo ${f.name}:\n${(await f.text()).slice(0,12000)}`;if(f.type.startsWith("image/")||f.type==="application/pdf")return`\n\nArchivo adjunto: ${f.name}. El backend actual no recibe binarios: no afirmes haber analizado su contenido.`;throw new Error("Tipo de archivo no permitido para el chat.");}

async function transmit(text){if(!text&&!config.attachment)return;bubble(text||`Archivo: ${config.attachment.name}`,"user");remember("usuario",text);const direct=localReply(text);if(direct&&!config.attachment){bubble(direct,"bot");remember("asistente",direct);speak(direct);status.textContent="Listo.";return;}status.textContent="El tutor está pensando…";try{const context=await attachmentContext();const history=config.wise?`\n\nContexto local reciente:\n${memory.slice(-8).map(x=>`${x.role}: ${x.text}`).join("\n")}`:"";const response=await fetch(`${api}/api/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mensaje:`${text}${context}${history}`,sessionId:localStorage.chongSession||(localStorage.chongSession=crypto.randomUUID()),requireSources:config.sources})});const data=await response.json();if(!response.ok)throw new Error(data.error||"El tutor no pudo responder.");const answer=data.respuesta||data.reply||"El tutor devolvió una respuesta vacía.";bubble(answer,"bot",Array.isArray(data.sources)?data.sources:[]);remember("asistente",answer);speak(answer);status.textContent="Listo para seguir.";}catch(error){const message=error.message||"No pude conectar con el tutor.";bubble(message,"bot");status.textContent="Necesito configuración.";}finally{config.attachment=null;fileInput.value="";fileName.textContent="";}}

form.addEventListener("submit",e=>{e.preventDefault();const text=field.value.trim();field.value="";transmit(text);});
$("#mode").addEventListener("click",e=>{document.body.classList.toggle("classic");e.currentTarget.textContent=document.body.classList.contains("classic")?"☀️ Clásico":"🌌 Interestelar";});
$("#chatToggle").addEventListener("click",()=>setChatOpen($(".chat").classList.contains("closed")));
$("#otterOrb").addEventListener("click",playWithOtter);$("#otterAction").addEventListener("click",playWithOtter);
$("#randomAction").addEventListener("click",()=>{setChatOpen(true);field.value=surprisePrompts[Math.floor(Math.random()*surprisePrompts.length)];field.focus();playWithOtter();});
$("#customizeAction").addEventListener("click",()=>{$("#customPanel").hidden=!$("#customPanel").hidden;});
$("#accentPicker").addEventListener("input",e=>{personality.accent=e.target.value;savePersonality();});
$("#motionToggle").addEventListener("change",e=>{personality.motion=e.target.checked;savePersonality();});
$("#resetCustom").addEventListener("click",()=>{personality.accent="#7fd0ff";personality.motion=true;savePersonality();});
$("#fileButton").addEventListener("click",()=>fileInput.click());
fileInput.addEventListener("change",()=>{const files=[...fileInput.files];if(files.length===2&&files.every(f=>f.type.startsWith("audio/"))){config.audioFiles=files;config.attachment=null;$("#mixerPanel").hidden=false;$("#mixNames").textContent=files.map(f=>f.name).join(" + ");fileName.textContent="2 pistas listas";bubble("Dos pistas cargadas. Ajustá niveles y pulsá Mezclar.","bot");}else{config.audioFiles=[];$("#mixerPanel").hidden=true;config.attachment=files[0]||null;fileName.textContent=config.attachment?config.attachment.name:"";if(files.length>1)bubble("Para mezclar, elegí exactamente dos archivos de audio. Para el chat se usará el primero.","bot");}});
$("#wiseButton").addEventListener("click",e=>{config.wise=!config.wise;e.currentTarget.setAttribute("aria-pressed",String(config.wise));bubble(`Memoria local ${config.wise?"activada":"pausada"}.`,"bot");});
$("#clearMemory").addEventListener("click",()=>{memory=[];localStorage.removeItem(MEMORY_KEY);messages.replaceChildren();bubble("Memoria y mensajes borrados. Arrancamos limpio.","bot");});
function toggleNitro(){config.nitro=!config.nitro;document.body.classList.toggle("nitro",config.nitro);$("#nitroButton").setAttribute("aria-pressed",String(config.nitro));}
$("#nitroButton").addEventListener("click",toggleNitro);
$(".brand").addEventListener("dblclick",toggleNitro);
$("#sourcesButton").addEventListener("click",e=>{config.sources=!config.sources;e.currentTarget.setAttribute("aria-pressed",String(config.sources));bubble(`Fuentes verificables ${config.sources?"exigidas":"desactivadas"}.`,"bot");});

const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
$("#voice").addEventListener("click",()=>{if(!Speech){bubble("Este navegador no soporta reconocimiento de voz.","bot");return;}const r=new Speech();r.lang="es-MX";r.interimResults=false;r.continuous=false;config.voiceReply=true;status.textContent="Escuchando…";r.onresult=e=>{field.value=e.results[0][0].transcript.trim();form.requestSubmit();};r.onerror=()=>bubble("No te escuché. Revisá el permiso del micrófono y probá otra vez.","bot");r.start();});

let audioContext=null,sources=[],gains=[];
function stopMix(){sources.forEach(s=>{try{s.stop();}catch{}});sources=[];if(audioContext){audioContext.close();audioContext=null;}}
$("#mixPlay").addEventListener("click",async()=>{stopMix();try{audioContext=new(window.AudioContext||window.webkitAudioContext)();const buffers=await Promise.all(config.audioFiles.map(async f=>audioContext.decodeAudioData(await f.arrayBuffer())));gains=[audioContext.createGain(),audioContext.createGain()];gains[0].gain.value=Number($("#gainA").value);gains[1].gain.value=Number($("#gainB").value);sources=buffers.map((buffer,i)=>{const s=audioContext.createBufferSource();s.buffer=buffer;s.connect(gains[i]).connect(audioContext.destination);s.start();return s;});bubble("Mezcla reproduciéndose. Ajustá los dos niveles en tiempo real.","bot");}catch{bubble("No pude decodificar esas pistas. Probá MP3, WAV u OGG compatibles con tu navegador.","bot");}});
$("#mixStop").addEventListener("click",stopMix);$("#gainA").addEventListener("input",e=>{if(gains[0])gains[0].gain.value=Number(e.target.value);});$("#gainB").addEventListener("input",e=>{if(gains[1])gains[1].gain.value=Number(e.target.value);});

document.querySelectorAll("[data-pay]").forEach(button=>button.addEventListener("click",async()=>{const out=$("#payState"),monto=Number($("#amount").value);if(monto<10||monto>100000){out.textContent="Monto inválido.";return;}out.textContent="Preparando pasarela…";try{const response=await fetch(`${api}/api/stripe-checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({monto,tipo:button.dataset.pay})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(window.nativeBridge)window.nativeBridge.openExternal(data.url);else location.assign(data.url);}catch(error){out.textContent=error.message||"No se pudo abrir Stripe.";}}));
$("#notify").addEventListener("click",async()=>{try{const p=await Notification.requestPermission();alert(p==="granted"?"Recordatorios habilitados.":"Permiso no concedido.");}catch{alert("Configura notificaciones desde los ajustes.");}});
function setupDonationShare(){const project="https://www.chongseb.com",short=`🦦 ¡Hola! Estoy armando un proyecto educativo con IA (${project}) y necesito probar el sistema de donaciones. ¿Me ayudás con $10 MXN? Es para verificar que Stripe → Supabase → Telegram funcione. El pago es seguro y está en la sección de donaciones. ¡Gracias por la mano! 🚀`,professional=`🌌 Hola, estoy desarrollando “NASA de Chong”, un proyecto educativo de IA: ${project}. Necesito validar el flujo completo de donaciones con una transacción real. ¿Podrías ayudarme con una donación simbólica de $10 MXN? El pago es seguro y verificable. Muchas gracias por el apoyo. 🦦🚀`,box=document.createElement("div");box.className="shareActions";const title=document.createElement("strong");title.textContent="Compartí la misión";box.append(title);[["WhatsApp",`https://wa.me/?text=${encodeURIComponent(short)}`],["Telegram",`https://t.me/share/url?url=${encodeURIComponent(project)}&text=${encodeURIComponent(short)}`],["LinkedIn",`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(project)}`]].forEach(([label,href])=>{const a=document.createElement("a");a.className="shareButton";a.href=href;a.target="_blank";a.rel="noopener noreferrer";a.textContent=label;box.append(a);});const copy=document.createElement("button");copy.type="button";copy.textContent="📋 Copiar texto LinkedIn";copy.addEventListener("click",async()=>{try{await copyText(professional);copy.textContent="✅ Copiado";}catch{copy.textContent="No se pudo copiar";}setTimeout(()=>copy.textContent="📋 Copiar texto LinkedIn",2000);});box.append(copy);$("#payState").after(box);}
setupDonationShare();savePersonality();messages.replaceChildren();bubble("Modo Sabio activado. La memoria queda solo en este dispositivo y podés borrarla con 🧹.","bot");
const route=location.pathname.replace(/\/+$/,"")||"/";if(route==="/clasico")document.body.classList.add("route-classic");if(route==="/viaje")document.body.classList.add("route-viaje");renderMissions();save();if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js");
