const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.join(__dirname,"..");
test("incluye superficies multiplataforma",()=>["apps/web/index.html","apps/desktop/main.cjs","apps/mobile/capacitor.config.json"].forEach(f=>assert.equal(fs.existsSync(path.join(root,f)),true,f)));
test("el cliente no contiene secretos",()=>{const text=fs.readFileSync(path.join(root,"apps/web/config.js"),"utf8");["SERVICE_ROLE","STRIPE_SECRET","PAYPAL_CLIENT_SECRET","TELEGRAM_BOT_TOKEN"].forEach(k=>assert.equal(text.includes(k),false,k))});
test("incluye identidad visual completa",()=>{const dir=path.join(root,"apps/web/assets/icon");[16,32,64,128,256,512,1024].forEach(s=>assert.ok(fs.statSync(path.join(dir,`icon-${s}.png`)).size>0));["nutria-astronauta.ico","nutria-astronauta.icns","social-profile-1024.png"].forEach(f=>assert.ok(fs.statSync(path.join(dir,f)).size>0,f))});
test("manifiesto referencia iconos existentes",()=>{const manifest=JSON.parse(fs.readFileSync(path.join(root,"apps/web/manifest.webmanifest"),"utf8"));manifest.icons.forEach(icon=>assert.ok(fs.existsSync(path.join(root,"apps/web",icon.src)),icon.src));assert.match(manifest.name,/Solo llámame nutria/)});
test("interfaz modo sabio usa motor externo compatible con CSP",()=>{const html=fs.readFileSync(path.join(root,"apps/web/index.html"),"utf8");["voice","fileButton","wiseButton","clearMemory","nitroButton","sourcesButton","fileInput","mixerPanel","mixPlay","mixStop"].forEach(id=>assert.match(html,new RegExp(`id=\\"${id}\\"`)));assert.match(html,/multiple accept="audio\/\*/);assert.doesNotMatch(html,/<script(?![^>]*src=)[^>]*>/i)});
test("rutas unificadas respetan API antes del fallback",()=>{const toml=fs.readFileSync(path.join(root,"backend/netlify.toml"),"utf8");assert.ok(toml.indexOf('from = "/api/*"')<toml.indexOf('from = "/*"'));assert.match(toml,/from = "\/clasico"/);assert.match(toml,/from = "\/viaje"/)});
test("los mensajes permanecen hasta que el usuario los borra",()=>{const app=fs.readFileSync(path.join(root,"apps/web/app.js"),"utf8");assert.doesNotMatch(app,/setTimeout\(\(\)=>article\.(?:classList\.add|remove)/);assert.match(app,/messages\.replaceChildren\(\)/)});
