create table if not exists donaciones (
  id uuid primary key default gen_random_uuid(), proveedor text not null check (proveedor in ('stripe','paypal','bitso')),
  proveedor_evento_id text not null, monto numeric(12,2) not null check (monto >= 0), moneda text not null default 'mxn',
  tipo text not null default 'unico' check (tipo in ('unico','mensual')), metadata jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now(), unique (proveedor, proveedor_evento_id)
);
create index if not exists idx_donaciones_creado_en on donaciones (creado_en desc);
alter table donaciones enable row level security;
drop policy if exists "sin acceso publico a donaciones" on donaciones;
create policy "sin acceso publico a donaciones" on donaciones for all using (false) with check (false);

create table if not exists tripulantes (
  id uuid primary key default gen_random_uuid(),
  alias varchar(50) not null unique,
  email varchar(254),
  caguamas integer not null default 0 check (caguamas >= 0),
  rango varchar(50) not null default 'Recluta',
  misiones_completadas text[] not null default '{}',
  ultimo_dia date,
  fecha_registro timestamptz not null default now()
);

create table if not exists logs (
  id bigint generated by default as identity primary key,
  accion varchar(100) not null,
  detalle text,
  metadata jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now()
);

alter table tripulantes enable row level security;
alter table logs enable row level security;
drop policy if exists "sin acceso publico a tripulantes" on tripulantes;
drop policy if exists "sin acceso publico a logs" on logs;
create policy "sin acceso publico a tripulantes" on tripulantes for all using (false) with check (false);
create policy "sin acceso publico a logs" on logs for all using (false) with check (false);
